services:
  db:
    image: postgres:16
    container_name: recetas-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init-products.sql:/docker-entrypoint-initdb.d/01-products.sql:ro
      - ./db/init-recipes.sql:/docker-entrypoint-initdb.d/02-recipes.sql:ro
      - ./db/init-shopping.sql:/docker-entrypoint-initdb.d/03-shopping.sql:ro
    networks:
      - recetas-net

  products-service:
    build: ./products-service
    container_name: productos-svc
    environment:
      DATABASE_URL: ${PRODUCTS_DATABASE_URL}
    depends_on:
      - db
    networks:
      - recetas-net

  recipes-service:
    build: ./recipes-service
    container_name: recetas-svc
    environment:
      DATABASE_URL: ${RECIPES_DATABASE_URL}
    depends_on:
      - db
    networks:
      - recetas-net

  shopping-service:
    build: ./shopping-service
    container_name: shopping-svc
    environment:
      DATABASE_URL: ${SHOPPING_DATABASE_URL}
    depends_on:
      - db
    networks:
      - recetas-net

  gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "8080:8080"          # expone el API Gateway
    depends_on:
      - products-service
      - recipes-service
      - shopping-service
    networks:
      - recetas-net

  web:
    image: nginx:alpine
    container_name: recetas-web
    ports:
      - "8090:80"            # front estático
    volumes:
      - ./web/index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - gateway
    networks:
      - recetas-net

volumes:
  db_data:

networks:
  recetas-net: